package com.enjoylearning.mybatis.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_position
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TPosition extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.post_name
     *
     * @mbg.generated
     */
    private String postName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.id
     *
     * @return the value of t_position.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.id
     *
     * @param id the value for t_position.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.post_name
     *
     * @return the value of t_position.post_name
     *
     * @mbg.generated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.post_name
     *
     * @param postName the value for t_position.post_name
     *
     * @mbg.generated
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.note
     *
     * @return the value of t_position.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.note
     *
     * @param note the value for t_position.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }
}