#!/usr/bin/env bash
#
# Copyright 2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -ev
export REDIS_REPLICATOR_HOME=`pwd`
cd ..
wget https://github.com/antirez/redis/archive/3.2.3.tar.gz
tar -xvzf 3.2.3.tar.gz
cd redis-3.2.3
make
cd src
nohup ./redis-server --port 6379 &
sleep 1
cd $REDIS_REPLICATOR_HOME
mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle
mvn clean install -DskipITs