notifications:
  email:
    recipients:
      - zhangke.huangshan@gmail.com
      - zhendongliu92@gmail.com
  on_success: change
  on_failure: always

language: java

matrix:
  include:
  # On OSX, run with default JDK only.
  # - os: osx
  # On Linux, run with specific JDKs only.
  # - os: linux
  #  env: CUSTOM_JDK="oraclejdk8"
  - os: linux
    env: CUSTOM_JDK="oraclejdk7"
  #- os: linux
  #  env: CUSTOM_JDK="openjdk7"

before_install:
  - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
  - cat ~/.mavenrc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi

#os:
#  - linux
#  - osx
#jdk:
#  - oraclejdk8
#  - oraclejdk7
#  - openjdk7


script:
  - travis_retry mvn -B clean install jacoco:report coveralls:report

#after_success:
#  - mvn clean install
#  - mvn sonar:sonar
