package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.THealthReportMale;
import com.enjoylearning.mybatis.entity.THealthReportMaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THealthReportMaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    long countByExample(THealthReportMaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int deleteByExample(THealthReportMaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int insert(THealthReportMale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int insertSelective(THealthReportMale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    List<THealthReportMale> selectByExample(THealthReportMaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    THealthReportMale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") THealthReportMale record, @Param("example") THealthReportMaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") THealthReportMale record, @Param("example") THealthReportMaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(THealthReportMale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_male
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(THealthReportMale record);
}