package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.TJobHistory;
import com.enjoylearning.mybatis.entity.TJobHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TJobHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    long countByExample(TJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int deleteByExample(TJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int insert(TJobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int insertSelective(TJobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    List<TJobHistory> selectByExample(TJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    TJobHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TJobHistory record, @Param("example") TJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TJobHistory record, @Param("example") TJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TJobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TJobHistory record);
}