package com.tuling.dao.model;

public class Tree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.position
     *
     * @mbggenerated
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.filters
     *
     * @mbggenerated
     */
    private String filters;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.id
     *
     * @return the value of tree.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.id
     *
     * @param id the value for tree.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.parent_id
     *
     * @return the value of tree.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.parent_id
     *
     * @param parentId the value for tree.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.position
     *
     * @return the value of tree.position
     *
     * @mbggenerated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.position
     *
     * @param position the value for tree.position
     *
     * @mbggenerated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.user_name
     *
     * @return the value of tree.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.user_name
     *
     * @param userName the value for tree.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.title
     *
     * @return the value of tree.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.title
     *
     * @param title the value for tree.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.filters
     *
     * @return the value of tree.filters
     *
     * @mbggenerated
     */
    public String getFilters() {
        return filters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.filters
     *
     * @param filters the value for tree.filters
     *
     * @mbggenerated
     */
    public void setFilters(String filters) {
        this.filters = filters == null ? null : filters.trim();
    }
}