server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/aaronrao/spring-cloud-config-test.git      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: zhuge                  # 配置登录的账号是user
    password: 123456       # 配置登录的密码是password123